import type { EraSlug, SourceRecord } from "@/lib/content/types";

export const sourceRecords: SourceRecord[] = [
  {
    id: "geocities",
    title: "GeoCities (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/GeoCities",
    type: "secondary",
    use: "Background on GeoCities culture and the democratization of web publishing.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "myspace",
    title: "Myspace (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Myspace",
    type: "secondary",
    use: "Context on customization culture, social profiles, and public identity performance.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "gif-history",
    title: "Graphics Interchange Format (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/GIF",
    type: "secondary",
    use: "History of GIF use and its role in early web animation.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "y2k-aesthetic",
    title: "Y2K aesthetic (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Y2K_aesthetic",
    type: "secondary",
    use: "Defines core Y2K visual traits and common motifs.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "web-badge",
    title: "Web badge (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Web_badge",
    type: "secondary",
    use: "Background on 88x31 badge culture and its role in early-web identity.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "archive-wayback",
    title: "Wayback Machine (Internet Archive)",
    url: "https://web.archive.org/",
    type: "archive",
    use: "Primary archive for preserved early-web pages and images used throughout the exhibit.",
    licenseNotes: "Archive access does not change original rights; confirm educational fair use where necessary.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "gifcities",
    title: "GifCities (Internet Archive)",
    url: "https://gifcities.org/",
    type: "archive",
    use: "Archive of GeoCities-era GIFs and buttons used as stylistic evidence.",
    licenseNotes: "Original GIFs may be copyrighted; cite original pages where possible.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "jordaneldredge-badges",
    title: "88x31 Archive (Jordan Eldredge)",
    url: "https://jordaneldredge.com/badges/",
    type: "directory",
    use: "Curated archive of classic web badges used to illustrate early-web identity signals.",
    licenseNotes: "Treat as a reference archive and attribute the site.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "geocities-uc-gif",
    title: "Under Construction GIF (GeoCities Archive Capture)",
    url: "https://web.archive.org/web/20091027105057/http://geocities.com/abu_ali22002/images/uc.gif",
    type: "image-asset",
    use: "Representative early-web GIF button for the visual archive.",
    licenseNotes: "Use low-resolution archival media with attribution for educational exhibit context.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "geocities-banner-gif",
    title: "Banner GIF (GeoCities Archive Capture)",
    url: "https://web.archive.org/web/20071202213854/http://us.share.geocities.com/dark13342/Dominani.gif",
    type: "image-asset",
    use: "Animated banner graphic representative of personal-page decoration.",
    licenseNotes: "Use as archival evidence with attribution to the archived source.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "geocities-panic-button",
    title: "Animated Button (GeoCities Archive Capture)",
    url: "https://web.archive.org/web/20010605113404/http://www.geocities.com:80/CollegePark/Classroom/2490/panic-f.gif",
    type: "image-asset",
    use: "Animated button example for early-web graphic language.",
    licenseNotes: "Use as archival evidence with attribution to the archived source.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "geocities-screenshot",
    title: "GeoCities Homepage Screenshot",
    url: "https://en.wikipedia.org/wiki/File:FirstGeocitiesYahoo.png",
    type: "image-asset",
    use: "Homepage screenshot used for home and early-web framing.",
    licenseNotes: "Source through Wikimedia page for media details and attribution.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "guestbook-archive",
    title: "GeoCities Guestbook Archive",
    url: "https://geocities.restorativland.org/EnchantedForest/Cottage/1233/geobook.html",
    type: "archive",
    use: "Illustrates public guestbook interaction and visible visitor traces.",
    licenseNotes: "Archive usage should remain documentary and attributed.",
    eras: ["early-web-aesthetics"],
  },
  {
    id: "flat-design",
    title: "Flat design (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Flat_design",
    type: "secondary",
    use: "Defines flat design principles and platform-era minimalism.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["platform-standardization"],
  },
  {
    id: "metro-design",
    title: "Metro design language (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Metro_(design_language)",
    type: "secondary",
    use: "Explains Microsoft's influence on content-first, grid-based UI trends.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["platform-standardization"],
  },
  {
    id: "material-design",
    title: "Material Design (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Material_Design",
    type: "secondary",
    use: "Documents Google's system for motion, depth, and component consistency.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["platform-standardization"],
  },
  {
    id: "start81",
    title: "Start81 Screenshot",
    url: "https://commons.wikimedia.org/wiki/File:Start81.png",
    type: "image-asset",
    use: "Metro tile interface example for platform-era visual archive.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["platform-standardization"],
  },
  {
    id: "material-you-light",
    title: "Material You Light",
    url: "https://commons.wikimedia.org/wiki/File:Material_you_light.png",
    type: "image-asset",
    use: "Material Design component example for system-level consistency.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["platform-standardization"],
  },
  {
    id: "windows10abstract",
    title: "Windows Abstract Graphic",
    url: "https://commons.wikimedia.org/wiki/File:Windows10abstract.png",
    type: "image-asset",
    use: "Flat design branding example showing color-block abstraction.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["platform-standardization"],
  },
  {
    id: "mobile-first-grid",
    title: "UI Tips: Common Types of Grid",
    url: "https://makeitclear.com/wp-content/uploads/2022/11/UI-tips-grids-common-types-of-grid.png",
    type: "image-asset",
    use: "Grid system illustration used for platform-era layout discipline.",
    licenseNotes: "Verify final usage rights before public deployment.",
    eras: ["platform-standardization"],
  },
  {
    id: "windows8-wikipedia",
    title: "Wikipedia App Snapped to Windows 8 Desktop",
    url: "https://commons.wikimedia.org/wiki/File:Wikipedia_App_snapped_to_Windows_8_desktop.png",
    type: "image-asset",
    use: "Component-based app layout illustrating modular platform-era UI.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["platform-standardization"],
  },
  {
    id: "infinite-scroll",
    title: "Infinite scroll (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Infinite_scroll",
    type: "secondary",
    use: "Explains feed-native layouts and scroll-optimized interaction patterns.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "attention-economy",
    title: "Attention economy (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Attention_economy",
    type: "secondary",
    use: "Frames how engagement incentives shape contemporary design decisions.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "ab-testing",
    title: "A/B testing (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/A/B_testing",
    type: "secondary",
    use: "Explains experimentation culture behind performance-driven interface changes.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "youtube-shorts",
    title: "YouTube Shorts Player Screenshot",
    url: "https://commons.wikimedia.org/wiki/File:YouTube_Shorts_player,_opened_on_a_video.png",
    type: "image-asset",
    use: "Short-form feed screenshot used to show infinite-scroll logic.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "analytics-dashboard",
    title: "Visitor Analytics Dashboard",
    url: "https://commons.wikimedia.org/wiki/File:Visitor_Analytics_Dashboard.jpg",
    type: "image-asset",
    use: "Analytics dashboard used for metrics-driven design evidence.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "responsive-devices",
    title: "Responsive Web Design Devices",
    url: "https://commons.wikimedia.org/wiki/File:Responsive-web-design-devices.jpg",
    type: "image-asset",
    use: "Responsive layout example for multi-device system design.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "signal-flow-diagram",
    title: "Graph Diagram (System Flow Stand-In)",
    url: "https://commons.wikimedia.org/wiki/File:Graph_SIR_model_without_vital_dynamics.svg",
    type: "image-asset",
    use: "Abstract diagram used as a visual stand-in for signal routing and ranking logic.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "internet-map",
    title: "Internet Map",
    url: "https://commons.wikimedia.org/wiki/File:Internet_map_1024_-_transparent,_inverted.png",
    type: "image-asset",
    use: "System abstraction image for hidden network infrastructure and algorithmic mediation.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["algorithmic-influence"],
  },
  {
    id: "internet-meme",
    title: "Internet meme (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Internet_meme",
    type: "secondary",
    use: "Overview of meme culture, remix practices, and shared digital authorship.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "vaporwave",
    title: "Vaporwave (Wikipedia)",
    url: "https://en.wikipedia.org/wiki/Vaporwave",
    type: "secondary",
    use: "Defines vaporwave aesthetics, origins, and its role in online subcultures.",
    licenseNotes: "Wikipedia text is CC BY-SA 4.0; attribute if quoting.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "brutalist-websites",
    title: "Brutalist Websites",
    url: "https://brutalistwebsites.com/",
    type: "directory",
    use: "Directory of raw and experimental web design used as reference for anti-design analysis.",
    licenseNotes: "Each listed site has its own rights; use as reference, not blanket license coverage.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "doge-meme",
    title: "Doge Meme Example",
    url: "https://commons.wikimedia.org/wiki/File:Doge_meme_example.jpg",
    type: "image-asset",
    use: "Meme format example for subculture archive.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "vaporwave-art",
    title: "Vaporwave Art Example",
    url: "https://commons.wikimedia.org/wiki/File:Vaporwave_art_example.png",
    type: "image-asset",
    use: "Vaporwave image used to illustrate remix and nostalgia aesthetics.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "fourchan",
    title: "4chan Screenshot",
    url: "https://commons.wikimedia.org/wiki/File:4chan.png",
    type: "image-asset",
    use: "Raw forum interface example for brutalist or anti-polish tendencies.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "deep-fried-meme",
    title: "Deep Fried Meme",
    url: "https://commons.wikimedia.org/wiki/File:Deep_fried_meme.jpg",
    type: "image-asset",
    use: "Example of intentionally degraded meme aesthetics.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "uk-us-zines",
    title: "UK and US Zines",
    url: "https://commons.wikimedia.org/wiki/File:UK_and_US_zines.jpg",
    type: "image-asset",
    use: "Zine spread used to represent manifesto culture and distributed authorship.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["subcultures-and-anti-design"],
  },
  {
    id: "twochan",
    title: "2chan Main Page",
    url: "https://commons.wikimedia.org/wiki/File:2chan_main_page.png",
    type: "image-asset",
    use: "Imageboard interface used to illustrate decentralized remix channels.",
    licenseNotes: "Review Wikimedia media page for attribution requirements.",
    eras: ["subcultures-and-anti-design"],
  },
];

export const licensingChecklist = [
  "Who owns the original media or screenshot?",
  "Is the asset CC-licensed, public domain, or otherwise usable for the exhibit?",
  "If not, does low-resolution educational fair use reasonably apply?",
  "Does the citation include the author or site name and a stable URL?",
];

export const eraSourceOrder: Array<{ slug: EraSlug; title: string }> = [
  { slug: "early-web-aesthetics", title: "Early Web Aesthetics" },
  { slug: "platform-standardization", title: "Platform Standardization" },
  { slug: "algorithmic-influence", title: "Algorithmic Influence" },
  { slug: "subcultures-and-anti-design", title: "Subcultures and Anti-Design" },
];